[versions]
# libraries
detekt-formatting = "1.23.8"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.10"
kover = "0.9.7"
qodana = "2025.2.1"
detekt = "1.23.8"

[libraries]
detektFormatting = {group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt-formatting"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
